### ISSUE TITLE
안녕하세요 혹시 해선 실시간 시세는 지원이 안될까요?

### ISSUE THREAD

**Issue by omszzz** [teranum/ls-openapi-samples#1]
안녕하세요

샘플에도 없어서 요청 코드 및 TR 코드 넣어서 해봤는데 작동이 안되서 문의 드립니다.

**Comment by teranum** [comment]
이슈 확인 늦었습니다.
해외 선물 조회/실시간 샘플 올렸어요 (24~27)
샘플 27  참고 하시면 해결 될 듯 합니다

**Comment by omszzz** [comment]
넵 감사합니다 C#으로는 없으신것이죠??

파이선에만 올라와 있어서 여쭤봅니다

**Comment by teranum** [comment]
c# 샘플도 새로 올렸습니다, 샘플 27 참고 하시면 됩니다

**Comment by teranum** [comment]
> 넵 감사합니다 C#으로는 없으신것이죠??
> 
> 파이선에만 올라와 있어서 여쭤봅니다

c# 샘플도 새로 올렸습니다, 샘플 27 참고 하시면 됩니다
